"""empty message

Revision ID: 8d250e716b46
Revises: 
Create Date: 2023-06-30 15:56:30.772466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d250e716b46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('username', sa.String(length=48), nullable=False),
    sa.Column('hashed_password', sa.Unicode(), nullable=False),
    sa.Column('display_name', sa.Unicode(), nullable=True),
    sa.Column('line_id', sa.Unicode(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('Boards',
    sa.Column('board_uuid', sa.String(length=48), nullable=False),
    sa.Column('administrator', sa.String(length=48), nullable=False),
    sa.Column('board_id', sa.Unicode(), nullable=False),
    sa.Column('board_name', sa.Unicode(), nullable=False),
    sa.Column('members', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['administrator'], ['Users.username'], ),
    sa.PrimaryKeyConstraint('board_uuid')
    )
    op.create_table('Subboards',
    sa.Column('subboard_uuid', sa.String(length=48), nullable=False),
    sa.Column('board_uuid', sa.String(length=48), nullable=False),
    sa.Column('subboard_name', sa.Unicode(), nullable=False),
    sa.Column('members', sa.Unicode(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['board_uuid'], ['Boards.board_uuid'], ),
    sa.PrimaryKeyConstraint('subboard_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Subboards')
    op.drop_table('Boards')
    op.drop_table('Users')
    # ### end Alembic commands ###
